# -*- coding: utf-8 -*-
"""Code_Source_Projet_Force_N.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wu9WVROhfc89kEZkhDEMvCX9n8oNah78
"""

# =============================================================================
# 1 : IMPORTS
# =============================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score
import joblib
import warnings
warnings.filterwarnings('ignore')

plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

print("✅ Bibliothèques importées avec succès !")

# =============================================================================
# 2 : CHARGEMENT DES DONNÉES
# =============================================================================

# Téléchargement
!kaggle datasets download -d atharvaingle/crop-recommendation-dataset
!unzip -o crop-recommendation-dataset.zip

# Chargement
df = pd.read_csv('Crop_recommendation.csv')
print(f"📊 Dataset chargé : {df.shape}")
display(df.head())

# =============================================================================
# 3 : ANALYSE EXPLORATOIRE
# =============================================================================

print("\n📊 STATISTIQUES DESCRIPTIVES")
print(df.describe())

print("\n🌾 DISTRIBUTION DES CULTURES")
print(df['label'].value_counts())

# Graphiques
plt.figure(figsize=(12, 6))
df['label'].value_counts().plot(kind='bar', color='skyblue', edgecolor='black')
plt.title('Distribution des Types de Cultures', fontsize=16)
plt.xlabel('Type de Culture')
plt.ylabel("Nombre d'échantillons")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# =============================================================================
# 4 : PRÉTRAITEMENT
# =============================================================================

# Séparation
X = df.drop('label', axis=1)
y = df['label']

# Encodage
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Normalisation
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

print(f"✅ Train : {X_train.shape[0]} échantillons")
print(f"✅ Test : {X_test.shape[0]} échantillons")

# Sauvegarde
np.save('X_train.npy', X_train)
np.save('X_test.npy', X_test)
np.save('y_train.npy', y_train)
np.save('y_test.npy', y_test)
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(label_encoder, 'label_encoder.pkl')

print("✅ Données sauvegardées")

# =============================================================================
# 5 : ENTRAÎNEMENT DES MODÈLES
# =============================================================================

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'XGBoost': XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')
}

results = {}
predictions = {}

for name, model in models.items():
    print(f"\n▶️ Entraînement de {name}...")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    predictions[name] = y_pred

    accuracy = accuracy_score(y_test, y_pred)
    f1_macro = f1_score(y_test, y_pred, average='macro')
    cv_scores = cross_val_score(model, X_train, y_train, cv=5)

    results[name] = {
        'Accuracy': accuracy,
        'F1-Score (macro)': f1_macro,
        'CV Mean': cv_scores.mean(),
        'CV Std': cv_scores.std()
    }

    print(f"   ✅ Accuracy: {accuracy:.4f}")
    print(f"   ✅ F1-Score: {f1_macro:.4f}")
    print(f"   ✅ CV Score: {cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")

# =============================================================================
# 6 : COMPARAISON ET MEILLEUR MODÈLE
# =============================================================================

results_df = pd.DataFrame(results).T
print("\n📊 COMPARAISON DES MODÈLES")
print(results_df.round(4))

best_name = results_df['Accuracy'].idxmax()
best_model = models[best_name]
y_pred_best = predictions[best_name]

print(f"\n🏆 MEILLEUR MODÈLE : {best_name}")
print(f"   Accuracy: {results[best_name]['Accuracy']:.4f}")

# Sauvegarde
joblib.dump(best_model, 'best_model.pkl')
print(f"✅ Modèle sauvegardé : best_model.pkl")

# Matrice de confusion
cm = confusion_matrix(y_test, y_pred_best)
plt.figure(figsize=(14, 12))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)
plt.title(f'Matrice de Confusion - {best_name}', fontsize=16)
plt.xlabel('Prédiction')
plt.ylabel('Vérité terrain')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# =============================================================================
# 7 : INTERFACE GRADIO
# =============================================================================

import gradio as gr

def predict_crop(N, P, K, temperature, humidity, ph, rainfall):
    best_model = joblib.load('best_model.pkl')
    scaler = joblib.load('scaler.pkl')
    label_encoder = joblib.load('label_encoder.pkl')

    features = np.array([[N, P, K, temperature, humidity, ph, rainfall]])
    features_scaled = scaler.transform(features)

    prediction = best_model.predict(features_scaled)
    prediction_proba = best_model.predict_proba(features_scaled)

    crop_name = label_encoder.inverse_transform(prediction)[0]
    confidence = np.max(prediction_proba) * 100

    top_indices = np.argsort(prediction_proba[0])[-5:][::-1]
    top_crops = label_encoder.inverse_transform(top_indices)
    top_probs = prediction_proba[0][top_indices] * 100

    recommendations_df = pd.DataFrame({
        'Culture': top_crops,
        'Confiance (%)': top_probs.round(1)
    })

    fig, ax = plt.subplots(figsize=(8, 6))
    colors = ['#2ecc71' if i == 0 else '#3498db' for i in range(len(top_crops))]
    bars = ax.barh(top_crops, top_probs, color=colors, edgecolor='black')
    ax.set_xlabel('Probabilité (%)')
    ax.set_title('Top 5 Cultures Recommandées', fontsize=14)
    ax.set_xlim(0, 105)

    for i, bar in enumerate(bars):
        width = bar.get_width()
        ax.text(width + 1, bar.get_y() + bar.get_height()/2,
                f'{top_probs[i]:.1f}%',
                va='center', fontweight='bold')
    plt.tight_layout()

    return crop_name, f"Confiance: {confidence:.1f}%", recommendations_df, fig

# Création de l'interface
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("""
    # 🌾 AgriPredict - Système de Recommandation de Cultures
    """)

    with gr.Row():
        with gr.Column(scale=2):
            N = gr.Slider(0, 140, value=50, label="Azote (N) kg/ha")
            P = gr.Slider(0, 145, value=40, label="Phosphore (P) kg/ha")
            K = gr.Slider(0, 205, value=30, label="Potassium (K) kg/ha")
            temperature = gr.Slider(15, 35, value=20, label="Température (°C)")
            humidity = gr.Slider(40, 90, value=60, label="Humidité (%)")
            ph = gr.Slider(4.5, 8.5, value=6.5, step=0.1, label="pH du Sol")
            rainfall = gr.Slider(50, 300, value=100, label="Pluviométrie (mm)")
            predict_btn = gr.Button("🌾 Prédire la Culture", variant="primary", size="lg")

        with gr.Column(scale=1):
            crop_output = gr.Textbox(label="🌾 Culture Recommandée", interactive=False)
            confidence_output = gr.Textbox(label="🎯 Confiance du Modèle", interactive=False)

    with gr.Row():
        recommendations_table = gr.Dataframe(
            headers=["Culture", "Confiance (%)"],
            label="📋 Top 5 Cultures Recommandées",
            interactive=False
        )
        plot_output = gr.Plot(label="📈 Probabilités par Culture")

    predict_btn.click(
        predict_crop,
        inputs=[N, P, K, temperature, humidity, ph, rainfall],
        outputs=[crop_output, confidence_output, recommendations_table, plot_output]
    )

# Lancement
demo.launch(share=True, debug=False)

# Monter Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Copier les fichiers vers Drive
!cp best_model.pkl /content/drive/MyDrive/
!cp scaler.pkl /content/drive/MyDrive/
!cp label_encoder.pkl /content/drive/MyDrive/
!cp Crop_recommendation.csv /content/drive/MyDrive/

print("✅ Fichiers sauvegardés dans Google Drive")

# Téléchargement individuel de chaque fichier
from google.colab import files

# Télécharger le modèle
files.download('best_model.pkl')

# Télécharger le scaler
files.download('scaler.pkl')

# Télécharger l'encodeur
files.download('label_encoder.pkl')

# Télécharger les données
files.download('Crop_recommendation.csv')

print("✅ Fichiers téléchargés")

# 1. Compresser tous les fichiers importants
!zip -r projet_force_n_livrables.zip \
    Crop_recommendation.csv \
    best_model.pkl \
    scaler.pkl \
    label_encoder.pkl \
    X_train.npy \
    X_test.npy \
    y_train.npy \
    y_test.npy \
    feature_names.txt \
    *.png

# 2. Télécharger le ZIP
from google.colab import files
files.download('projet_force_n_livrables.zip')

# =============================================================================
# GÉNÉRATION DE TOUS LES GRAPHIQUES DU PROJET
# =============================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
import joblib
import warnings
warnings.filterwarnings('ignore')

# Configuration
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# Chargement des données
df = pd.read_csv('Crop_recommendation.csv')
print("✅ Données chargées")

# =============================================================================
# GRAPHIQUE 1 : Distribution des cultures (barres)
# =============================================================================

def graphique_distribution_cultures(df):
    """Graphique de la distribution des cultures"""
    plt.figure(figsize=(12, 6))
    culture_counts = df['label'].value_counts()
    culture_counts.plot(kind='bar', color='skyblue', edgecolor='black')
    plt.title('Distribution des Types de Cultures', fontsize=16)
    plt.xlabel('Type de Culture', fontsize=12)
    plt.ylabel("Nombre d'échantillons", fontsize=12)
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.savefig('culture_distribution.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("✅ Graphique 1 : culture_distribution.png")

graphique_distribution_cultures(df)


# =============================================================================
# GRAPHIQUE 2 : Distribution des variables numériques
# =============================================================================

def graphique_distributions_variables(df):
    """Histogrammes des variables numériques"""
    fig, axes = plt.subplots(2, 4, figsize=(16, 10))
    axes = axes.flatten()

    for idx, col in enumerate(df.columns[:-1]):  # Exclure 'label'
        sns.histplot(df[col], kde=True, ax=axes[idx])
        axes[idx].set_title(f'Distribution de {col}', fontsize=12)
        axes[idx].set_xlabel(col)

    # Cacher les axes vides (7 variables, 8 sous-graphiques)
    for idx in range(len(df.columns[:-1]), len(axes)):
        axes[idx].set_visible(False)

    plt.tight_layout()
    plt.savefig('distributions.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("✅ Graphique 2 : distributions.png")

graphique_distributions_variables(df)


# =============================================================================
# GRAPHIQUE 3 : Boxplots par culture
# =============================================================================

def graphique_boxplots_culture(df):
    """Boxplots de chaque variable par culture"""
    fig, axes = plt.subplots(2, 4, figsize=(16, 10))
    axes = axes.flatten()

    for idx, col in enumerate(df.columns[:-1]):
        sns.boxplot(data=df, x='label', y=col, ax=axes[idx])
        axes[idx].set_title(f'{col} par Culture', fontsize=12)
        axes[idx].set_xlabel('')
        axes[idx].tick_params(axis='x', rotation=45)

    for idx in range(len(df.columns[:-1]), len(axes)):
        axes[idx].set_visible(False)

    plt.tight_layout()
    plt.savefig('boxplots_by_culture.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("✅ Graphique 3 : boxplots_by_culture.png")

graphique_boxplots_culture(df)


# =============================================================================
# GRAPHIQUE 4 : Matrice de corrélation
# =============================================================================

def graphique_correlation(df):
    """Matrice de corrélation"""
    plt.figure(figsize=(10, 8))
    corr_matrix = df[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']].corr()
    sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f',
                linewidths=0.5, square=True)
    plt.title('Matrice de Corrélation des Variables', fontsize=16)
    plt.tight_layout()
    plt.savefig('correlation_matrix.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("✅ Graphique 4 : correlation_matrix.png")

graphique_correlation(df)


# =============================================================================
# GRAPHIQUE 5 : Moyennes des variables par culture
# =============================================================================

def graphique_moyennes_culture(df):
    """Moyennes des variables par culture"""
    fig, axes = plt.subplots(2, 4, figsize=(16, 10))
    axes = axes.flatten()

    for idx, col in enumerate(df.columns[:-1]):
        means = df.groupby('label')[col].mean().sort_values()
        means.plot(kind='bar', ax=axes[idx], color='coral', edgecolor='black')
        axes[idx].set_title(f'Moyenne de {col} par Culture', fontsize=12)
        axes[idx].set_xlabel('')
        axes[idx].tick_params(axis='x', rotation=45)

    for idx in range(len(df.columns[:-1]), len(axes)):
        axes[idx].set_visible(False)

    plt.tight_layout()
    plt.savefig('means_by_culture.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("✅ Graphique 5 : means_by_culture.png")

graphique_moyennes_culture(df)


# =============================================================================
# GRAPHIQUE 6 : Boxplots des outliers
# =============================================================================

def graphique_outliers(df):
    """Boxplots pour détection des outliers"""
    fig, axes = plt.subplots(2, 4, figsize=(16, 10))
    axes = axes.flatten()

    for idx, col in enumerate(df.columns[:-1]):
        sns.boxplot(data=df, y=col, ax=axes[idx])
        axes[idx].set_title(f'Boxplot de {col}', fontsize=12)

    for idx in range(len(df.columns[:-1]), len(axes)):
        axes[idx].set_visible(False)

    plt.tight_layout()
    plt.savefig('boxplots_outliers.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("✅ Graphique 6 : boxplots_outliers.png")

graphique_outliers(df)


# =============================================================================
# GRAPHIQUE 7 : Répartition des cultures (camembert)
# =============================================================================

def graphique_pie_cultures(df):
    """Camembert des cultures"""
    culture_pct = df['label'].value_counts()

    plt.figure(figsize=(10, 8))
    plt.pie(culture_pct.values, labels=culture_pct.index, autopct='%1.1f%%',
            startangle=90, shadow=True)
    plt.title('Répartition des Cultures dans le Dataset', fontsize=16)
    plt.tight_layout()
    plt.savefig('culture_pie_chart.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("✅ Graphique 7 : culture_pie_chart.png")

graphique_pie_cultures(df)


# =============================================================================
# GRAPHIQUE 8 : Distribution Train/Test
# =============================================================================

def graphique_train_test(df):
    """Distribution des classes dans train et test"""
    # Préparation des données
    X = df.drop('label', axis=1)
    y = df['label']
    label_encoder = LabelEncoder()
    y_encoded = label_encoder.fit_transform(y)
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
    )

    # Graphique
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    # Train
    train_counts = np.bincount(y_train)
    train_cultures = [label_encoder.inverse_transform([i])[0] for i in range(len(train_counts))]
    axes[0].barh(train_cultures, train_counts, color='skyblue', edgecolor='black')
    axes[0].set_title('Distribution des Cultures - Train Set', fontsize=14)
    axes[0].set_xlabel("Nombre d'échantillons")

    # Test
    test_counts = np.bincount(y_test)
    test_cultures = [label_encoder.inverse_transform([i])[0] for i in range(len(test_counts))]
    axes[1].barh(test_cultures, test_counts, color='lightgreen', edgecolor='black')
    axes[1].set_title('Distribution des Cultures - Test Set', fontsize=14)
    axes[1].set_xlabel("Nombre d'échantillons")

    plt.tight_layout()
    plt.savefig('distributions_train_test.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("✅ Graphique 8 : distributions_train_test.png")

graphique_train_test(df)


# =============================================================================
# GRAPHIQUE 9 : Comparaison des modèles
# =============================================================================

def graphique_comparaison_modeles():
    """Comparaison des performances des modèles"""
    # Résultats (à adapter selon vos modèles)
    results = {
        'Logistic Regression': {'Accuracy': 0.9727, 'F1-Score': 0.9725, 'CV Mean': 0.9676, 'CV Std': 0.0113},
        'Decision Tree': {'Accuracy': 0.9795, 'F1-Score': 0.9794, 'CV Mean': 0.9847, 'CV Std': 0.0071},
        'Random Forest': {'Accuracy': 0.9955, 'F1-Score': 0.9955, 'CV Mean': 0.9932, 'CV Std': 0.0043},
        'XGBoost': {'Accuracy': 0.9909, 'F1-Score': 0.9908, 'CV Mean': 0.9892, 'CV Std': 0.0049}
    }

    results_df = pd.DataFrame(results).T

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    # Métriques
    results_df[['Accuracy', 'F1-Score', 'CV Mean']].plot(
        kind='bar', ax=axes[0], color=['#3498db', '#2ecc71', '#e74c3c']
    )
    axes[0].set_title('Comparaison des Métriques par Modèle', fontsize=14)
    axes[0].set_ylabel('Score')
    axes[0].set_xlabel('Modèles')
    axes[0].legend(loc='lower right')
    axes[0].set_ylim(0.8, 1.0)
    axes[0].grid(axis='y', alpha=0.3)

    # CV
    axes[1].bar(results_df.index, results_df['CV Mean'],
                yerr=results_df['CV Std'], capsize=5,
                color=['#3498db', '#2ecc71', '#e74c3c', '#9b59b6'])
    axes[1].set_title('Validation Croisée (CV=5)', fontsize=14)
    axes[1].set_ylabel('Score Moyen')
    axes[1].set_xlabel('Modèles')
    axes[1].set_ylim(0.8, 1.0)
    axes[1].grid(axis='y', alpha=0.3)

    plt.tight_layout()
    plt.savefig('model_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("✅ Graphique 9 : model_comparison.png")

# Note : Ce graphique nécessite que les modèles soient entraînés

graphique_comparaison_modeles()


# =============================================================================
# GRAPHIQUE 10 : Matrice de confusion
# =============================================================================

def graphique_confusion_matrix():
    """Matrice de confusion du meilleur modèle"""
    try:
        # Charger le modèle et les données
        best_model = joblib.load('best_model.pkl')
        label_encoder = joblib.load('label_encoder.pkl')
        X_test = np.load('X_test.npy')
        y_test = np.load('y_test.npy')

        # Prédictions
        y_pred = best_model.predict(X_test)

        # Matrice de confusion
        cm = confusion_matrix(y_test, y_pred)

        plt.figure(figsize=(14, 12))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                    xticklabels=label_encoder.classes_,
                    yticklabels=label_encoder.classes_)
        plt.title('Matrice de Confusion - Random Forest', fontsize=16)
        plt.xlabel('Prédiction', fontsize=12)
        plt.ylabel('Vérité terrain', fontsize=12)
        plt.xticks(rotation=45, ha='right')
        plt.yticks(rotation=0)
        plt.tight_layout()
        plt.savefig('confusion_matrix.png', dpi=300, bbox_inches='tight')
        plt.show()
        print("✅ Graphique 10 : confusion_matrix.png")

    except FileNotFoundError:
        print("⚠️ Modèle non trouvé. Entraînez d'abord le modèle.")

graphique_confusion_matrix()


# =============================================================================
# TÉLÉCHARGEMENT DE TOUS LES GRAPHIQUES
# =============================================================================

def telecharger_tous_les_graphes():
    """Télécharge tous les graphiques en ZIP"""
    import zipfile
    from google.colab import files

    # Liste des graphiques
    graphes = [
        'culture_distribution.png',
        'distributions.png',
        'boxplots_by_culture.png',
        'correlation_matrix.png',
        'means_by_culture.png',
        'boxplots_outliers.png',
        'culture_pie_chart.png',
        'distributions_train_test.png',
        'model_comparison.png',
        'confusion_matrix.png'
    ]

    # Créer un dossier
    import os
    os.makedirs('graphes', exist_ok=True)

    # Copier les graphiques existants
    for g in graphes:
        if os.path.exists(g):
            !cp {g} graphes/
            print(f"✅ {g} copié")
        else:
            print(f"⚠️ {g} non trouvé")

    # Compresser
    with zipfile.ZipFile('tous_les_graphes.zip', 'w') as zipf:
        for root, dirs, filenames in os.walk('graphes'): # Renamed 'files' to 'filenames'
            for file in filenames:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, 'graphes')
                zipf.write(file_path, arcname)

    print("\n✅ Archive créée : tous_les_graphes.zip")

    # Télécharger
    files.download('tous_les_graphes.zip')

# Exécuter
telecharger_tous_les_graphes()

import joblib

# Charger le modèle
with open("best_model.pkl", "rb") as f:
    model = joblib.load(f)

print(model)

